# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170420_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='agemax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='agemin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='headteacher',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='localauthority',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='urn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
